// Render the bow (craftofexile id_base 20) mod pool + derived per-slam odds into
// crafting/reference/bow-affix-weights.md. Source snapshot: data/reference/bow-id20-mods.json
// (craftofexile ?game=poe2&b=20). Every EV input in the bow sim traces back to this table.

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

interface Tier {
  ilvl: number;
  weight: number;
  values: number[][];
}
interface Mod {
  name: string;
  tiers: Tier[];
}
interface Pool {
  source: string;
  ilvl: number;
  note: string;
  prefixes: Mod[];
  suffixes: Mod[];
}

const ROOT = join(fileURLToPath(new URL(".", import.meta.url)), "../..");
const FLOORS = [0, 35, 50]; // Exalt, Greater Exalt (min 35), Perfect Exalt (min 50)

const fmtVals = (v: number[][]) =>
  v
    .map((p) => {
      const lo = p?.[0];
      const hi = p?.[1] ?? lo;
      if (lo == null && hi == null) return "?";
      if (lo == null) return `${hi}`;
      return lo === hi ? `${lo}` : `${lo}–${hi}`;
    })
    .join(", ");

function modRows(mods: Mod[]): string {
  return mods
    .map((m) => {
      const tiers = m.tiers.map((t) => `T@${t.ilvl} w${t.weight} (${fmtVals(t.values)})`).join(" · ");
      return `| ${m.name} | ${tiers} |`;
    })
    .join("\n");
}

/** Total weight of a pool with every tier required-level ≥ floor (and ≤ item ilvl). */
function poolWeight(mods: Mod[], floor: number, ilvl: number, only?: (m: Mod) => boolean): number {
  let w = 0;
  for (const m of mods) {
    if (only && !only(m)) continue;
    for (const t of m.tiers) if (t.ilvl >= floor && t.ilvl <= ilvl) w += t.weight;
  }
  return w;
}

/** Weight of one named mod restricted to tiers at/above a minimum required level. */
function modWeight(mods: Mod[], name: string, floor: number, ilvl: number, minTierIlvl = 0): number {
  const m = mods.find((x) => x.name === name);
  if (!m) return 0;
  return m.tiers
    .filter((t) => t.ilvl >= Math.max(floor, minTierIlvl) && t.ilvl <= ilvl)
    .reduce((s, t) => s + t.weight, 0);
}

export function generateBowWeights(): string {
  const pool = JSON.parse(
    readFileSync(join(ROOT, "data/reference/bow-id20-mods.json"), "utf8"),
  ) as Pool;
  const { ilvl } = pool;

  const CRIT = "+#% to Critical Hit Chance";
  const AS = "#% increased Attack Speed";
  const CD = "+#% to Critical Damage Bonus";
  // Damage prefixes = anything mentioning Physical or an element + Damage/Attacks.
  const isDmgPrefix = (m: Mod) => /Physical|Lightning|Fire|Cold|Elemental/i.test(m.name);

  const sharesRows = FLOORS.map((f) => {
    const orb = f === 0 ? "Exalted Orb" : f === 35 ? "Greater Exalted (min 35)" : "Perfect Exalted (min 50)";
    const sufTot = poolWeight(pool.suffixes, f, ilvl);
    const preTot = poolWeight(pool.prefixes, f, ilvl);
    const critAll = modWeight(pool.suffixes, CRIT, f, ilvl);
    const critT3 = modWeight(pool.suffixes, CRIT, f, ilvl, 44); // T3 = ilvl 44+
    const asW = modWeight(pool.suffixes, AS, f, ilvl) + modWeight(pool.suffixes, CD, f, ilvl);
    const dmgPre = poolWeight(pool.prefixes, f, ilvl, isDmgPrefix);
    const pct = (n: number, d: number) => (d ? ((100 * n) / d).toFixed(1) + "%" : "—");
    return `| ${orb} | ${pct(dmgPre, preTot)} | ${pct(critAll, sufTot)} | ${pct(critT3, sufTot)} | ${pct(asW, sufTot)} |`;
  }).join("\n");

  return `# Bow affix weights — craftofexile id_base 20 (Obliterator / Warmonger)

> Generated by \`pnpm reference\` from \`data/reference/bow-id20-mods.json\`.
> Source: ${pool.source}. ${pool.note}. Item ilvl ${ilvl}.
> Refresh the JSON snapshot from craftofexile when the patch changes weights.

These are the spawn weights every bow-craft EV number derives from. A modifier's **tier
required level** (\`T@N\`) is what the level-floor exalts gate on: an **Exalted Orb** can roll
any tier, **Greater Exalted** only tiers with required level ≥ 35, **Perfect Exalted** only
≥ 50. So a higher exalt guarantees a higher *tier* but also shrinks the pool — changing the
per-slam *type* odds below.

## Derived per-slam odds (by exalt floor)

P(the added mod is the target), top-tier crafting reads straight off the weights:

| Orb | dmg prefix | crit (any tier) | crit ≥T3 | attack-speed or crit-dmg |
|---|---|---|---|---|
${sharesRows}

> Note the trade-off: crit's share *falls* as the floor rises (its high tiers are a small
> slice of the high-tier pool), but every crit you do land is a better tier. **Greater Exalt
> (min 35)** is the sweet spot for crit ≥T3; **Perfect (min 50)** forces T2+ but is rarer.

## Prefixes (Σ weights shown per tier: T@requiredLevel · weight · value)

| Prefix | Tiers |
|---|---|
${modRows(pool.prefixes)}

## Suffixes

| Suffix | Tiers |
|---|---|
${modRows(pool.suffixes)}
`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  writeFileSync(join(ROOT, "crafting/reference/bow-affix-weights.md"), generateBowWeights());
  console.log("✓ wrote crafting/reference/bow-affix-weights.md");
}
