// Generate the local crafting reference (crafting/reference/*.md) from poe2db.tw so the
// exact effect text of every omen / currency / essence / bone lives in-repo and never has
// to be recalled from memory. Re-run with `pnpm reference` to refresh after a patch.
//
// Output is plain-text Markdown tables: name · key field (min mod level) · exact effect.
// poe2db is the datamined source of truth; prices are NOT here (see data/economy).

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { discoverSlugs, fetchAll, type RefItem } from "./poe2db.js";
import { generateBowWeights } from "./bow-weights.js";

const OUT_DIR = join(fileURLToPath(new URL(".", import.meta.url)), "../../crafting/reference");

// Currency orbs relevant to rare-item crafting (the level-floor exalts are the headline).
const CURRENCY = [
  "Orb_of_Transmutation", "Orb_of_Augmentation", "Regal_Orb", "Greater_Regal_Orb", "Perfect_Regal_Orb",
  "Exalted_Orb", "Greater_Exalted_Orb", "Perfect_Exalted_Orb",
  "Orb_of_Annulment", "Orb_of_Alchemy", "Chaos_Orb", "Greater_Chaos_Orb", "Perfect_Chaos_Orb",
  "Divine_Orb", "Vaal_Orb", "Fracturing_Orb", "Orb_of_Chance", "Mirror_of_Kalandra",
  "Artificers_Orb", "Gemcutters_Prism", "Glassblowers_Bauble", "Blacksmiths_Whetstone", "Armourers_Scrap",
];

function table(items: Array<RefItem | null>): string {
  return items
    .filter((it): it is RefItem => it !== null && it.effect.length > 0)
    .map((it) => `| ${it.name} | ${it.minModLevel ?? "—"} | ${it.effect} |`)
    .join("\n");
}

function md(title: string, intro: string, header: string, body: string): string {
  return `# ${title}

> Generated by \`pnpm reference\` from poe2db.tw. Do not hand-edit — re-run to refresh.
> Exact effect text is datamined; prices live in \`data/economy\`.

${intro}

${header}
${body}
`;
}

async function main() {
  mkdirSync(OUT_DIR, { recursive: true });

  // Bones aren't linked by slug on the list page, so enumerate them (Cranium = jewels,
  // only the Preserved variant exists).
  const boneSlugs = [
    "Gnawed_Jawbone", "Gnawed_Collarbone", "Gnawed_Rib",
    "Preserved_Jawbone", "Preserved_Collarbone", "Preserved_Rib", "Preserved_Cranium",
    "Ancient_Jawbone", "Ancient_Collarbone", "Ancient_Rib",
  ];

  console.log("· discovering omen / essence slugs from poe2db list pages …");
  const [omenSlugs, essenceSlugs] = await Promise.all([
    discoverSlugs("Omen", "Omen_of_[A-Za-z0-9_]+"),
    discoverSlugs("Essence", "(?:Greater_|Perfect_)?Essence_of_[A-Za-z0-9_]+"),
  ]);
  console.log(`  omens ${omenSlugs.length} · essences ${essenceSlugs.length} · bones ${boneSlugs.length}`);

  console.log("· fetching item pages …");
  const [omens, currency, bones, essences] = await Promise.all([
    fetchAll(omenSlugs),
    fetchAll(CURRENCY),
    fetchAll(boneSlugs),
    fetchAll(essenceSlugs),
  ]);

  // --- Omens: split item-crafting omens from map/ritual/combat ones ---
  const isCrafting = (it: RefItem) =>
    (/your next (Exalted Orb|Orb of Annulment|Chaos Orb|Regal Orb|Orb of Alchemy|Divine Orb|Vaal Orb|Fracturing Orb|Orb of Transmutation|Orb of Augmentation)/i.test(
      it.effect,
    ) ||
      /desecrat|reveal .*modifier|Well of Souls/i.test(it.effect)) &&
    !/Waystone|Map|Pinnacle|Boss|Monster|Pack Size|Rarity|Quantity/i.test(it.effect);
  const omenItems = omens.filter((it): it is RefItem => it !== null && it.effect.length > 0);
  const craftOmens = omenItems.filter(isCrafting);
  const otherOmens = omenItems.filter((it) => !isCrafting(it));

  writeFileSync(
    join(OUT_DIR, "omens.md"),
    md(
      "Omens",
      "Omens consume on the **next** matching action. Sinistral = prefixes, Dextral = suffixes. " +
        "Crafting omens act on your next currency use; the rest (map/ritual/combat) are listed after.",
      "## Crafting omens\n\n| Omen | Effect |\n|---|---|",
      craftOmens.map((it) => `| ${it.name} | ${it.effect} |`).join("\n") +
        "\n\n## Other omens (map / ritual / combat)\n\n| Omen | Effect |\n|---|---|\n" +
        otherOmens.map((it) => `| ${it.name} | ${it.effect} |`).join("\n"),
    ),
  );

  writeFileSync(
    join(OUT_DIR, "currency.md"),
    md(
      "Currency",
      "The level-floor exalts are the headline: **Greater = min mod level 35**, **Perfect = min " +
        "mod level 50** — they restrict the *tier* of the added mod (and thus its pool share), they " +
        "do NOT guarantee the top tier.",
      "| Currency | Min mod level | Effect |\n|---|---|---|",
      table(currency),
    ),
  );

  writeFileSync(
    join(OUT_DIR, "bones.md"),
    md(
      "Desecration bones (Well of Souls)",
      "Bones add a desecrated modifier; the bone's **minimum modifier level** sets the floor of " +
        "what can be revealed. Gnawed caps item level (low), Preserved has no floor, Ancient = min " +
        "mod level 40 (high tiers only). Jawbone/Collarbone/Rib/Cranium select the slot pool.",
      "| Bone | Min mod level | Effect |\n|---|---|---|",
      table(bones),
    ),
  );

  writeFileSync(
    join(OUT_DIR, "essences.md"),
    md(
      "Essences",
      "Essences upgrade a **Magic** item to Rare while guaranteeing one modifier (one essence per " +
        "item). Greater/Perfect variants raise the guaranteed tier. They CANNOT be used on an item " +
        "that is already Rare (e.g. a bought fractured base).",
      "| Essence | Effect |\n|---|---|",
      essences
        .filter((it): it is RefItem => it !== null && it.effect.length > 0)
        .map((it) => `| ${it.name} | ${it.effect} |`)
        .join("\n"),
    ),
  );

  // Bow affix weights are derived from the committed craftofexile snapshot (no network).
  writeFileSync(join(OUT_DIR, "bow-affix-weights.md"), generateBowWeights());

  writeFileSync(
    join(OUT_DIR, "README.md"),
    `# Crafting reference (local)

Plain-text, in-repo copies of exact crafting mechanics so they're always referenceable.
Effects are datamined from poe2db.tw; bow weights from craftofexile. **Refresh:** \`pnpm reference\`.

| File | What |
|---|---|
| [currency.md](currency.md) | Orbs — incl. Greater (min mod lvl 35) / Perfect (min 50) exalt floors |
| [omens.md](omens.md) | Every omen's exact effect — Sinistral=prefix, Dextral=suffix |
| [bones.md](bones.md) | Desecration bones — min mod level + slot pool |
| [essences.md](essences.md) | Essence mechanic (Magic→Rare, one per item) |
| [bow-affix-weights.md](bow-affix-weights.md) | id_base 20 mod pool + per-slam odds by exalt floor |

Raw snapshot for the sim: \`data/reference/bow-id20-mods.json\`.
`,
  );

  console.log(
    `✓ wrote omens (${craftOmens.length} crafting), currency (${CURRENCY.length}), bones, essences, bow-affix-weights, README → ${OUT_DIR}`,
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
